import { normalizeWasmDiagnostics } from './diagnostics-model.js';

export function normalizeWasmState(input) {
  const value = input || {};
  const diagnostics = normalizeWasmDiagnostics(value);
  return {
    enabled: !!value.enabled,
    configured_enabled: !!value.configured_enabled,
    fallback_to_builtin_click: value.fallback_to_builtin_click !== false,
    configured_manifest_path: `${value.configured_manifest_path || ''}`.trim(),
    configured_manifest_path_click: `${value.configured_manifest_path_click || ''}`.trim(),
    configured_manifest_path_trail: `${value.configured_manifest_path_trail || ''}`.trim(),
    configured_manifest_path_scroll: `${value.configured_manifest_path_scroll || ''}`.trim(),
    configured_manifest_path_hold: `${value.configured_manifest_path_hold || ''}`.trim(),
    configured_manifest_path_hover: `${value.configured_manifest_path_hover || ''}`.trim(),
    configured_manifest_path_cursor_decoration: `${value.configured_manifest_path_cursor_decoration || ''}`.trim(),
    configured_catalog_root_path: `${value.configured_catalog_root_path || ''}`.trim(),
    configured_output_buffer_bytes: Number(value.configured_output_buffer_bytes) || 0,
    configured_max_commands: Number(value.configured_max_commands) || 0,
    configured_max_execution_ms: Number(value.configured_max_execution_ms) || 0,
    runtime_output_buffer_bytes: Number(value.runtime_output_buffer_bytes) || 0,
    runtime_max_commands: Number(value.runtime_max_commands) || 0,
    runtime_max_execution_ms: Number(value.runtime_max_execution_ms) || 0,
    last_call_duration_us: diagnostics.last_call_duration_us,
    last_output_bytes: diagnostics.last_output_bytes,
    last_command_count: diagnostics.last_command_count,
    last_call_exceeded_budget: diagnostics.last_call_exceeded_budget,
    last_call_rejected_by_budget: diagnostics.last_call_rejected_by_budget,
    last_output_truncated_by_budget: diagnostics.last_output_truncated_by_budget,
    last_command_truncated_by_budget: diagnostics.last_command_truncated_by_budget,
    last_budget_reason: diagnostics.last_budget_reason,
    last_parse_error: diagnostics.last_parse_error,
    last_load_failure_stage: diagnostics.last_load_failure_stage,
    last_load_failure_code: diagnostics.last_load_failure_code,
    runtime_backend: `${value.runtime_backend || ''}`.trim(),
    runtime_fallback_reason: `${value.runtime_fallback_reason || ''}`.trim(),
    plugin_loaded: !!value.plugin_loaded,
    plugin_api_version: Number(value.plugin_api_version) || 0,
    active_plugin_id: `${value.active_plugin_id || ''}`.trim(),
    active_plugin_name: `${value.active_plugin_name || ''}`.trim(),
    active_manifest_path: `${value.active_manifest_path || ''}`.trim(),
    active_wasm_path: `${value.active_wasm_path || ''}`.trim(),
    plugin_loaded_click: !!value.plugin_loaded_click,
    active_plugin_id_click: `${value.active_plugin_id_click || ''}`.trim(),
    active_plugin_name_click: `${value.active_plugin_name_click || ''}`.trim(),
    active_manifest_path_click: `${value.active_manifest_path_click || ''}`.trim(),
    active_wasm_path_click: `${value.active_wasm_path_click || ''}`.trim(),
    plugin_loaded_trail: !!value.plugin_loaded_trail,
    active_plugin_id_trail: `${value.active_plugin_id_trail || ''}`.trim(),
    active_plugin_name_trail: `${value.active_plugin_name_trail || ''}`.trim(),
    active_manifest_path_trail: `${value.active_manifest_path_trail || ''}`.trim(),
    active_wasm_path_trail: `${value.active_wasm_path_trail || ''}`.trim(),
    plugin_loaded_scroll: !!value.plugin_loaded_scroll,
    active_plugin_id_scroll: `${value.active_plugin_id_scroll || ''}`.trim(),
    active_plugin_name_scroll: `${value.active_plugin_name_scroll || ''}`.trim(),
    active_manifest_path_scroll: `${value.active_manifest_path_scroll || ''}`.trim(),
    active_wasm_path_scroll: `${value.active_wasm_path_scroll || ''}`.trim(),
    plugin_loaded_hold: !!value.plugin_loaded_hold,
    active_plugin_id_hold: `${value.active_plugin_id_hold || ''}`.trim(),
    active_plugin_name_hold: `${value.active_plugin_name_hold || ''}`.trim(),
    active_manifest_path_hold: `${value.active_manifest_path_hold || ''}`.trim(),
    active_wasm_path_hold: `${value.active_wasm_path_hold || ''}`.trim(),
    plugin_loaded_hover: !!value.plugin_loaded_hover,
    active_plugin_id_hover: `${value.active_plugin_id_hover || ''}`.trim(),
    active_plugin_name_hover: `${value.active_plugin_name_hover || ''}`.trim(),
    active_manifest_path_hover: `${value.active_manifest_path_hover || ''}`.trim(),
    active_wasm_path_hover: `${value.active_wasm_path_hover || ''}`.trim(),
    plugin_loaded_cursor_decoration: !!value.plugin_loaded_cursor_decoration,
    active_plugin_id_cursor_decoration: `${value.active_plugin_id_cursor_decoration || ''}`.trim(),
    active_plugin_name_cursor_decoration: `${value.active_plugin_name_cursor_decoration || ''}`.trim(),
    active_manifest_path_cursor_decoration: `${value.active_manifest_path_cursor_decoration || ''}`.trim(),
    active_wasm_path_cursor_decoration: `${value.active_wasm_path_cursor_decoration || ''}`.trim(),
    last_rendered_by_wasm: !!value.last_rendered_by_wasm,
    last_executed_text_commands: Number(value.last_executed_text_commands) || 0,
    last_executed_image_commands: Number(value.last_executed_image_commands) || 0,
    last_executed_pulse_commands: Number(value.last_executed_pulse_commands) || 0,
    last_executed_polyline_commands: Number(value.last_executed_polyline_commands) || 0,
    last_executed_path_stroke_commands: Number(value.last_executed_path_stroke_commands) || 0,
    last_executed_path_fill_commands: Number(value.last_executed_path_fill_commands) || 0,
    last_executed_glow_batch_commands: Number(value.last_executed_glow_batch_commands) || 0,
    last_executed_sprite_batch_commands: Number(value.last_executed_sprite_batch_commands) || 0,
    last_executed_glow_emitter_commands: Number(value.last_executed_glow_emitter_commands) || 0,
    last_executed_glow_emitter_remove_commands: Number(value.last_executed_glow_emitter_remove_commands) || 0,
    last_executed_sprite_emitter_commands: Number(value.last_executed_sprite_emitter_commands) || 0,
    last_executed_sprite_emitter_remove_commands: Number(value.last_executed_sprite_emitter_remove_commands) || 0,
    last_executed_particle_emitter_commands: Number(value.last_executed_particle_emitter_commands) || 0,
    last_executed_particle_emitter_remove_commands: Number(value.last_executed_particle_emitter_remove_commands) || 0,
    last_executed_ribbon_trail_commands: Number(value.last_executed_ribbon_trail_commands) || 0,
    last_executed_ribbon_trail_remove_commands: Number(value.last_executed_ribbon_trail_remove_commands) || 0,
    last_executed_quad_field_commands: Number(value.last_executed_quad_field_commands) || 0,
    last_executed_quad_field_remove_commands: Number(value.last_executed_quad_field_remove_commands) || 0,
    last_executed_group_remove_commands: Number(value.last_executed_group_remove_commands) || 0,
    last_executed_group_presentation_commands: Number(value.last_executed_group_presentation_commands) || 0,
    last_executed_group_clip_rect_commands: Number(value.last_executed_group_clip_rect_commands) || 0,
    last_executed_group_layer_commands: Number(value.last_executed_group_layer_commands) || 0,
    last_executed_group_transform_commands: Number(value.last_executed_group_transform_commands) || 0,
    last_executed_group_local_origin_commands: Number(value.last_executed_group_local_origin_commands) || 0,
    last_executed_group_material_commands: Number(value.last_executed_group_material_commands) || 0,
    last_executed_group_pass_commands: Number(value.last_executed_group_pass_commands) || 0,
    last_throttled_render_commands: Number(value.last_throttled_render_commands) || 0,
    last_throttled_by_capacity_render_commands: Number(value.last_throttled_by_capacity_render_commands) || 0,
    last_throttled_by_interval_render_commands: Number(value.last_throttled_by_interval_render_commands) || 0,
    last_dropped_render_commands: Number(value.last_dropped_render_commands) || 0,
    lifetime_invoke_calls: Number(value.lifetime_invoke_calls) || 0,
    lifetime_invoke_success_calls: Number(value.lifetime_invoke_success_calls) || 0,
    lifetime_invoke_failed_calls: Number(value.lifetime_invoke_failed_calls) || 0,
    lifetime_invoke_duration_us: Number(value.lifetime_invoke_duration_us) || 0,
    lifetime_invoke_exceeded_budget_calls: Number(value.lifetime_invoke_exceeded_budget_calls) || 0,
    lifetime_invoke_rejected_by_budget_calls: Number(value.lifetime_invoke_rejected_by_budget_calls) || 0,
    lifetime_render_dispatches: Number(value.lifetime_render_dispatches) || 0,
    lifetime_rendered_by_wasm_dispatches: Number(value.lifetime_rendered_by_wasm_dispatches) || 0,
    lifetime_executed_text_commands: Number(value.lifetime_executed_text_commands) || 0,
    lifetime_executed_image_commands: Number(value.lifetime_executed_image_commands) || 0,
    lifetime_executed_pulse_commands: Number(value.lifetime_executed_pulse_commands) || 0,
    lifetime_executed_polyline_commands: Number(value.lifetime_executed_polyline_commands) || 0,
    lifetime_executed_path_stroke_commands: Number(value.lifetime_executed_path_stroke_commands) || 0,
    lifetime_executed_path_fill_commands: Number(value.lifetime_executed_path_fill_commands) || 0,
    lifetime_executed_glow_batch_commands: Number(value.lifetime_executed_glow_batch_commands) || 0,
    lifetime_executed_sprite_batch_commands: Number(value.lifetime_executed_sprite_batch_commands) || 0,
    lifetime_executed_glow_emitter_commands: Number(value.lifetime_executed_glow_emitter_commands) || 0,
    lifetime_executed_glow_emitter_remove_commands: Number(value.lifetime_executed_glow_emitter_remove_commands) || 0,
    lifetime_executed_sprite_emitter_commands: Number(value.lifetime_executed_sprite_emitter_commands) || 0,
    lifetime_executed_sprite_emitter_remove_commands: Number(value.lifetime_executed_sprite_emitter_remove_commands) || 0,
    lifetime_executed_particle_emitter_commands: Number(value.lifetime_executed_particle_emitter_commands) || 0,
    lifetime_executed_particle_emitter_remove_commands: Number(value.lifetime_executed_particle_emitter_remove_commands) || 0,
    lifetime_executed_ribbon_trail_commands: Number(value.lifetime_executed_ribbon_trail_commands) || 0,
    lifetime_executed_ribbon_trail_remove_commands: Number(value.lifetime_executed_ribbon_trail_remove_commands) || 0,
    lifetime_executed_quad_field_commands: Number(value.lifetime_executed_quad_field_commands) || 0,
    lifetime_executed_quad_field_remove_commands: Number(value.lifetime_executed_quad_field_remove_commands) || 0,
    lifetime_executed_group_remove_commands: Number(value.lifetime_executed_group_remove_commands) || 0,
    lifetime_executed_group_presentation_commands: Number(value.lifetime_executed_group_presentation_commands) || 0,
    lifetime_executed_group_clip_rect_commands: Number(value.lifetime_executed_group_clip_rect_commands) || 0,
    lifetime_executed_group_layer_commands: Number(value.lifetime_executed_group_layer_commands) || 0,
    lifetime_executed_group_transform_commands: Number(value.lifetime_executed_group_transform_commands) || 0,
    lifetime_executed_group_local_origin_commands: Number(value.lifetime_executed_group_local_origin_commands) || 0,
    lifetime_executed_group_material_commands: Number(value.lifetime_executed_group_material_commands) || 0,
    lifetime_executed_group_pass_commands: Number(value.lifetime_executed_group_pass_commands) || 0,
    lifetime_throttled_render_commands: Number(value.lifetime_throttled_render_commands) || 0,
    lifetime_throttled_by_capacity_render_commands: Number(value.lifetime_throttled_by_capacity_render_commands) || 0,
    lifetime_throttled_by_interval_render_commands: Number(value.lifetime_throttled_by_interval_render_commands) || 0,
    lifetime_dropped_render_commands: Number(value.lifetime_dropped_render_commands) || 0,
    last_error: `${value.last_error || ''}`.trim(),
    last_render_error: `${value.last_render_error || ''}`.trim(),
    retained_glow_emitter_upsert_requests: Number(value.retained_glow_emitter_upsert_requests) || 0,
    retained_glow_emitter_remove_requests: Number(value.retained_glow_emitter_remove_requests) || 0,
    retained_glow_emitter_active_count: Number(value.retained_glow_emitter_active_count) || 0,
    retained_sprite_emitter_upsert_requests: Number(value.retained_sprite_emitter_upsert_requests) || 0,
    retained_sprite_emitter_remove_requests: Number(value.retained_sprite_emitter_remove_requests) || 0,
    retained_sprite_emitter_active_count: Number(value.retained_sprite_emitter_active_count) || 0,
    retained_particle_emitter_upsert_requests: Number(value.retained_particle_emitter_upsert_requests) || 0,
    retained_particle_emitter_remove_requests: Number(value.retained_particle_emitter_remove_requests) || 0,
    retained_particle_emitter_active_count: Number(value.retained_particle_emitter_active_count) || 0,
    retained_ribbon_trail_upsert_requests: Number(value.retained_ribbon_trail_upsert_requests) || 0,
    retained_ribbon_trail_remove_requests: Number(value.retained_ribbon_trail_remove_requests) || 0,
    retained_ribbon_trail_active_count: Number(value.retained_ribbon_trail_active_count) || 0,
    retained_quad_field_upsert_requests: Number(value.retained_quad_field_upsert_requests) || 0,
    retained_quad_field_remove_requests: Number(value.retained_quad_field_remove_requests) || 0,
    retained_quad_field_active_count: Number(value.retained_quad_field_active_count) || 0,
  };
}
