export const CARD_SECTIONS = [
  {
    id: 'general',
    cardClass: 'card-general',
    titleKey: 'section_general',
    titleDefault: 'General',
    descKey: 'desc_general',
    descDefault: 'Pick language, theme, and hold behavior before fine tuning.',
    mountId: 'general_settings_mount',
  },
  {
    id: 'mouse-companion',
    cardClass: 'card-mouse-companion',
    titleKey: 'section_mouse_companion',
    titleDefault: 'Mouse Companion',
    descKey: 'desc_mouse_companion',
    descDefault: 'Configure cursor companion model, follow profile, and test parameters.',
    mountId: 'mouse_companion_settings_mount',
  },
  {
    id: 'active',
    cardClass: 'card-effects',
    titleKey: 'section_effects',
    titleDefault: 'Cursor Effects',
    descKey: 'desc_effects',
    descDefault: 'Choose effects for each interaction, customize text content, and fine-tune trail rendering.',
    mountId: 'effects_settings_mount',
  },
  {
    id: 'input-indicator',
    cardClass: 'card-input',
    titleKey: 'section_input_indicator',
    titleDefault: 'Input Indicator',
    descKey: 'desc_input_indicator',
    descDefault: 'Configure visual feedback for click, wheel, and keyboard input.',
    mountId: 'input_indicator_settings_mount',
  },
  {
    id: 'cursor-decoration',
    cardClass: 'card-input',
    titleKey: 'section_cursor_decoration',
    titleDefault: 'Cursor Decoration',
    descKey: 'desc_cursor_decoration',
    descDefault: 'Attach a persistent cursor decorator plugin such as a ring, orb, or meteor head.',
    mountId: 'cursor_decoration_settings_mount',
  },
  {
    id: 'automation',
    cardClass: 'card-automation',
    titleKey: 'section_automation',
    titleDefault: 'Automation Mapping',
    descKey: 'desc_automation',
    descDefault: 'Map mouse actions and gestures to keyboard shortcuts.',
    mountId: 'automation_editor_mount',
    wrapperClass: 'grid',
    mountClass: 'span2',
  },
  {
    id: 'plugins',
    cardClass: 'card-wasm',
    titleKey: 'section_plugins',
    titleDefault: 'Plugin Management',
    descKey: 'desc_plugins',
    descDefault: 'Import, export, and inspect plugin catalog for effects and input-indicator plugins.',
    mountId: 'plugin_management_mount',
  },
];
