export const CARD_SECTIONS = [
  {
    id: 'general',
    cardClass: 'card-general',
    titleKey: 'section_general',
    titleDefault: 'General',
    descKey: 'desc_general',
    descDefault: 'Pick language, theme, and hold behavior before fine tuning.',
    mountId: 'general_settings_mount',
  },
  {
    id: 'active',
    cardClass: 'card-effects',
    titleKey: 'section_effects',
    titleDefault: 'Active Effects',
    descKey: 'desc_effects',
    descDefault: 'Select the runtime effect for each mouse interaction channel.',
    mountId: 'effects_settings_mount',
  },
  {
    id: 'input-indicator',
    cardClass: 'card-input',
    titleKey: 'section_input_indicator',
    titleDefault: 'Input Indicator',
    descKey: 'desc_input_indicator',
    descDefault: 'Configure visual feedback for click, wheel, and keyboard input.',
    mountId: 'input_indicator_settings_mount',
  },
  {
    id: 'text',
    cardClass: 'card-text',
    titleKey: 'section_text',
    titleDefault: 'Text Content (Click/Text)',
    descKey: 'desc_text',
    descDefault: 'Maintain your click text vocabulary and typography in one place.',
    mountId: 'text_settings_mount',
  },
  {
    id: 'automation',
    cardClass: 'card-automation',
    titleKey: 'section_automation',
    titleDefault: 'Automation Mapping',
    descKey: 'desc_automation',
    descDefault: 'Map mouse actions and gestures to keyboard shortcuts.',
    mountId: 'automation_editor_mount',
    wrapperClass: 'grid',
    mountClass: 'span2',
  },
  {
    id: 'wasm',
    cardClass: 'card-wasm',
    titleKey: 'section_wasm_plugin',
    titleDefault: 'Effect Plugins',
    descKey: 'desc_wasm_plugin',
    descDefault: 'Manage effect plugins and runtime diagnostics.',
    mountId: 'wasm_settings_mount',
  },
  {
    id: 'trail',
    cardClass: 'card-trail',
    titleKey: 'section_trail_tuning',
    titleDefault: 'Trail Tuning',
    descKey: 'desc_trail',
    descDefault: 'Adjust trail history and renderer parameters with predictable safe limits.',
    mountId: 'trail_settings_mount',
  },
];
