export const SAMPLE_PRESETS = [
  {
    key: "text-rise",
    source: "assembly/samples/effects/text-rise.ts",
    id: "demo.click.text-rise.v2",
    name: "Demo Click Text Rise",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "indicator-basic",
    source: "assembly/samples/indicator/input-indicator-basic.ts",
    id: "demo.indicator.basic.v2",
    name: "Demo Indicator Basic",
    version: "0.1.0",
    surfaces: ["indicator"],
    inputKinds: ["indicator_click", "indicator_scroll", "indicator_key"],
    enableFrameTick: false,
  },
  {
    key: "text-burst",
    source: "assembly/samples/effects/text-burst.ts",
    id: "demo.click.text-burst.v2",
    name: "Demo Click Text Burst",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "text-spiral",
    source: "assembly/samples/effects/text-spiral.ts",
    id: "demo.click.text-spiral.v2",
    name: "Demo Click Text Spiral",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "text-wave-chain",
    source: "assembly/samples/effects/text-wave-chain.ts",
    id: "demo.click.text-wave-chain.v2",
    name: "Demo Click Text Wave Chain",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "image-pulse",
    source: "assembly/samples/effects/image-pulse.ts",
    id: "demo.click.image-pulse.v2",
    name: "Demo Click Image Pulse",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/smile.png",
      "assets/coin.jpg",
      "assets/cat.gif",
      "assets/star.bmp",
    ],
  },
  {
    key: "image-burst",
    source: "assembly/samples/effects/image-burst.ts",
    id: "demo.click.image-burst.v2",
    name: "Demo Click Image Burst",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/confetti.png",
      "assets/crown.png",
      "assets/cat.gif",
    ],
  },
  {
    key: "image-lift",
    source: "assembly/samples/effects/image-lift.ts",
    id: "demo.click.image-lift.v2",
    name: "Demo Click Image Lift",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/lift-a.tif",
      "assets/lift-b.tiff",
    ],
  },
  {
    key: "mixed-text-image",
    source: "assembly/samples/effects/mixed-text-image.ts",
    id: "demo.click.mixed-text-image.v2",
    name: "Demo Click Mixed Text Image",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/crown.png",
      "assets/confetti.png",
    ],
  },
  {
    key: "mixed-emoji-celebrate",
    source: "assembly/samples/effects/mixed-emoji-celebrate.ts",
    id: "demo.click.mixed-emoji-celebrate.v2",
    name: "Demo Click Mixed Emoji Celebrate",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/party.gif",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "button-adaptive",
    source: "assembly/samples/effects/button-adaptive.ts",
    id: "demo.click.button-adaptive.v2",
    name: "Demo Click Button Adaptive",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/btn-left.png",
      "assets/btn-right.gif",
      "assets/btn-middle.tiff",
    ],
  },
  {
    key: "click-pulse-dual",
    source: "assembly/samples/effects/click-pulse-dual.ts",
    id: "demo.click.pulse-dual.v2",
    name: "Demo Click Pulse Dual",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-polyline-zigzag",
    source: "assembly/samples/effects/click-polyline-zigzag.ts",
    id: "demo.click.polyline-zigzag.v2",
    name: "Demo Click Polyline Zigzag",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-path-stroke-ribbon",
    source: "assembly/samples/effects/click-path-stroke-ribbon.ts",
    id: "demo.click.path-stroke-ribbon.v2",
    name: "Demo Click Path Stroke Ribbon",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-path-fill-badge",
    source: "assembly/samples/effects/click-path-fill-badge.ts",
    id: "demo.click.path-fill-badge.v2",
    name: "Demo Click Path Fill Badge",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-path-fill-clip-window",
    source: "assembly/samples/effects/click-path-fill-clip-window.ts",
    id: "demo.click.path-fill-clip-window.v2",
    name: "Demo Click Path Fill Clip Window",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-path-clip-lanes",
    source: "assembly/samples/effects/click-path-clip-lanes.ts",
    id: "demo.click.path-clip-lanes.v2",
    name: "Demo Click Path Clip Lanes",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-ribbon-trace",
    source: "assembly/samples/effects/click-ribbon-trace.ts",
    id: "demo.click.ribbon-trace.v2",
    name: "Demo Click Ribbon Trace",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-retained-ribbon-trail",
    source: "assembly/samples/effects/click-retained-ribbon-trail.ts",
    id: "demo.click.retained-ribbon-trail.v2",
    name: "Demo Click Retained Ribbon Trail",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-glow-burst",
    source: "assembly/samples/effects/click-glow-burst.ts",
    id: "demo.click.glow-burst.v2",
    name: "Demo Click Glow Burst",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-sprite-burst",
    source: "assembly/samples/effects/click-sprite-burst.ts",
    id: "demo.click.sprite-burst.v2",
    name: "Demo Click Sprite Burst",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-quad-atlas-burst",
    source: "assembly/samples/effects/click-quad-atlas-burst.ts",
    id: "demo.click.quad-atlas-burst.v2",
    name: "Demo Click Quad Atlas Burst",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-glow-field",
    source: "assembly/samples/effects/click-retained-glow-field.ts",
    id: "demo.click.retained-glow-field.v2",
    name: "Demo Click Retained Glow Field",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-retained-sprite-fountain",
    source: "assembly/samples/effects/click-retained-sprite-fountain.ts",
    id: "demo.click.retained-sprite-fountain.v2",
    name: "Demo Click Retained Sprite Fountain",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-particle-field",
    source: "assembly/samples/effects/click-retained-particle-field.ts",
    id: "demo.click.retained-particle-field.v2",
    name: "Demo Click Retained Particle Field",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
  },
  {
    key: "click-retained-quad-field",
    source: "assembly/samples/effects/click-retained-quad-field.ts",
    id: "demo.click.retained-quad-field.v2",
    name: "Demo Click Retained Quad Field",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-clear",
    source: "assembly/samples/effects/click-retained-group-clear.ts",
    id: "demo.click.retained-group-clear.v2",
    name: "Demo Click Retained Group Clear",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-alpha",
    source: "assembly/samples/effects/click-retained-group-alpha.ts",
    id: "demo.click.retained-group-alpha.v2",
    name: "Demo Click Retained Group Alpha",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-clip",
    source: "assembly/samples/effects/click-retained-group-clip.ts",
    id: "demo.click.retained-group-clip.v2",
    name: "Demo Click Retained Group Clip",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-layer",
    source: "assembly/samples/effects/click-retained-group-layer.ts",
    id: "demo.click.retained-group-layer.v2",
    name: "Demo Click Retained Group Layer",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-mask",
    source: "assembly/samples/effects/click-retained-group-mask.ts",
    id: "demo.click.retained-group-mask.v2",
    name: "Demo Click Retained Group Mask",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-transform",
    source: "assembly/samples/effects/click-retained-group-transform.ts",
    id: "demo.click.retained-group-transform.v2",
    name: "Demo Click Retained Group Transform",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-local-origin",
    source: "assembly/samples/effects/click-retained-group-local-origin.ts",
    id: "demo.click.retained-group-local-origin.v2",
    name: "Demo Click Retained Group Local Origin",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-material",
    source: "assembly/samples/effects/click-retained-group-material.ts",
    id: "demo.click.retained-group-material.v2",
    name: "Demo Click Retained Group Material",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "click-retained-group-pass",
    source: "assembly/samples/effects/click-retained-group-pass.ts",
    id: "demo.click.retained-group-pass.v2",
    name: "Demo Click Retained Group Pass",
    version: "0.1.0",
    inputKinds: ["click"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
      "assets/confetti.png",
      "assets/crown.png",
    ],
  },
  {
    key: "move-stream-sparks",
    source: "assembly/samples/effects/move-stream-sparks.ts",
    id: "demo.event.move-stream-sparks.v2",
    name: "Demo Event Move Stream Sparks",
    version: "0.1.0",
    inputKinds: ["move"],
    enableFrameTick: false,
  },
  {
    key: "cursor-decoration-focus-ring",
    source: "assembly/samples/effects/cursor-decoration-focus-ring.ts",
    id: "demo.cursor-decoration.focus-ring.v2",
    name: "Demo Cursor Decoration Focus Ring",
    version: "0.1.0",
    inputKinds: ["move"],
    enableFrameTick: true,
  },
  {
    key: "cursor-decoration-soft-orb",
    source: "assembly/samples/effects/cursor-decoration-soft-orb.ts",
    id: "demo.cursor-decoration.soft-orb.v2",
    name: "Demo Cursor Decoration Soft Orb",
    version: "0.1.0",
    inputKinds: ["move"],
    enableFrameTick: true,
  },
  {
    key: "cursor-decoration-halo-orb",
    source: "assembly/samples/effects/cursor-decoration-halo-orb.ts",
    id: "demo.cursor-decoration.halo-orb.v2",
    name: "Demo Cursor Decoration Halo Orb",
    version: "0.1.0",
    inputKinds: ["move"],
    enableFrameTick: true,
  },
  {
    key: "scroll-particle-burst",
    source: "assembly/samples/effects/scroll-particle-burst.ts",
    id: "demo.event.scroll-particle-burst.v2",
    name: "Demo Event Scroll Particle Burst",
    version: "0.1.0",
    inputKinds: ["scroll"],
    enableFrameTick: false,
    imageAssets: [
      "assets/smile.png",
      "assets/confetti.png",
      "assets/party.gif",
      "assets/emoji-2.png",
    ],
  },
  {
    key: "scroll-neon-burst",
    source: "assembly/samples/effects/scroll-neon-burst.ts",
    id: "demo.event.scroll-neon-burst.v2",
    name: "Demo Event Scroll Neon Burst",
    version: "0.1.0",
    inputKinds: ["scroll"],
    enableFrameTick: false,
    imageAssets: [
      "assets/particle-glow.png",
    ],
  },
  {
    key: "hold-orbit-pulse",
    source: "assembly/samples/effects/hold-orbit-pulse.ts",
    id: "demo.event.hold-orbit-pulse.v2",
    name: "Demo Event Hold Orbit Pulse",
    version: "0.1.0",
    inputKinds: ["hold_start", "hold_update", "hold_end"],
    enableFrameTick: false,
  },
  {
    key: "hover-spark-ring",
    source: "assembly/samples/effects/hover-spark-ring.ts",
    id: "demo.event.hover-spark-ring.v2",
    name: "Demo Event Hover Spark Ring",
    version: "0.1.0",
    inputKinds: ["hover_start", "hover_end"],
    enableFrameTick: false,
  },
];

export function findSamplePreset(key) {
  const value = `${key || ""}`.trim().toLowerCase();
  return SAMPLE_PRESETS.find((sample) => sample.key.toLowerCase() === value) || null;
}

export function sampleKeysText() {
  return SAMPLE_PRESETS.map((sample) => sample.key).join(", ");
}
