#pragma once

// Package-target platform selection.
// CMake package targets can override host macros via MFX_TARGET_PLATFORM_*.
#if defined(MFX_TARGET_PLATFORM_WINDOWS)
#define MFX_PLATFORM_WINDOWS 1
#define MFX_PLATFORM_MACOS 0
#define MFX_PLATFORM_LINUX 0
#define MFX_PLATFORM_UNKNOWN 0
#elif defined(MFX_TARGET_PLATFORM_MACOS)
#define MFX_PLATFORM_WINDOWS 0
#define MFX_PLATFORM_MACOS 1
#define MFX_PLATFORM_LINUX 0
#define MFX_PLATFORM_UNKNOWN 0
#elif defined(MFX_TARGET_PLATFORM_LINUX)
#define MFX_PLATFORM_WINDOWS 0
#define MFX_PLATFORM_MACOS 0
#define MFX_PLATFORM_LINUX 1
#define MFX_PLATFORM_UNKNOWN 0
#elif defined(_WIN32)
#define MFX_PLATFORM_WINDOWS 1
#define MFX_PLATFORM_MACOS 0
#define MFX_PLATFORM_LINUX 0
#define MFX_PLATFORM_UNKNOWN 0
#elif defined(__APPLE__)
#define MFX_PLATFORM_WINDOWS 0
#define MFX_PLATFORM_MACOS 1
#define MFX_PLATFORM_LINUX 0
#define MFX_PLATFORM_UNKNOWN 0
#elif defined(__linux__)
#define MFX_PLATFORM_WINDOWS 0
#define MFX_PLATFORM_MACOS 0
#define MFX_PLATFORM_LINUX 1
#define MFX_PLATFORM_UNKNOWN 0
#else
#define MFX_PLATFORM_WINDOWS 0
#define MFX_PLATFORM_MACOS 0
#define MFX_PLATFORM_LINUX 0
#define MFX_PLATFORM_UNKNOWN 1
#endif
